"""0002

Revision ID: 0002
Revises: 0001
Create Date: 2025-08-06 20:44:21.272217

"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('name', sa.String(), nullable=False))
    op.add_column('activities', sa.Column('organisation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activities', 'organizations', ['organisation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'organisation_id')
    op.drop_column('activities', 'name')
    # ### end Alembic commands ###
