"""0003

Revision ID: 0003
Revises: 0002
Create Date: 2025-08-06 21:02:43.123265

"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('activities_organisation_id_fkey'), 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('activities', 'organisation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('organisation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key(op.f('activities_organisation_id_fkey'), 'activities', 'organizations', ['organisation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('activities', 'organization_id')
    # ### end Alembic commands ###
